# Generated by Django 2.2.3 on 2019-07-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='стихия')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='название на русском')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='название на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, null=True, verbose_name='название на японском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('element_type', models.ManyToManyField(blank=True, null=True, to='pokemon_entities.PokemonElementType')),
                ('next_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokemon_entities.PokemonTemp', verbose_name='в кого эволюционирует')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokemon_entities.PokemonTemp', verbose_name='из кого эволюционировал')),
            ],
        ),
    ]
