# Generated by Django 2.2.3 on 2019-07-24 14:39

from django.db import migrations


def combine_pokemons(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    PokemonTemp = apps.get_model('pokemon_entities', 'PokemonTemp')
    for pokemon in Pokemon.objects.all():
        pokemon_temp = PokemonTemp()
        pokemon_temp.title_ru = pokemon.title_ru
        pokemon_temp.title_en = pokemon.title_en
        pokemon_temp.title_jp = pokemon.title_jp
        pokemon_temp.image = pokemon.image
        pokemon_temp.description = pokemon.description

        if pokemon.next_evolution:
            pokemon_temp_next_evolution = PokemonTemp()
            pokemon_temp_next_evolution.title_ru = pokemon.next_evolution.title_ru
            pokemon_temp_next_evolution.title_en = pokemon.next_evolution.title_en
            pokemon_temp_next_evolution.title_jp = pokemon.next_evolution.title_jp
            pokemon_temp_next_evolution.image = pokemon.next_evolution.image
            pokemon_temp_next_evolution.description = pokemon.next_evolution.description
            pokemon_temp.next_evolution = pokemon_temp_next_evolution
            pokemon_temp_next_evolution.save()

        if pokemon.previous_evolution:
            pokemon_temp_previous_evolution = PokemonTemp()
            pokemon_temp_previous_evolution.title_ru = pokemon.previous_evolution.title_ru
            pokemon_temp_previous_evolution.title_en = pokemon.previous_evolution.title_en
            pokemon_temp_previous_evolution.title_jp = pokemon.previous_evolution.title_jp
            pokemon_temp_previous_evolution.image = pokemon.previous_evolution.image
            pokemon_temp_previous_evolution.description = pokemon.previous_evolution.description
            pokemon_temp.previous_evolution = pokemon_temp_previous_evolution
            pokemon_temp_previous_evolution.save()

        pokemon_temp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20190724_1436'),
    ]

    operations = [
        migrations.RunPython(combine_pokemons),
    ]
