# Generated by Django 2.2.3 on 2019-07-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20190724_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType'),
        ),
        migrations.DeleteModel(
            name='PokemonTemp',
        ),
    ]
