# Generated by Django 2.2.3 on 2019-07-27 15:25

from django.db import migrations


def combine_pokemons(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    PokemonEntity = apps.get_model('pokemon_entities', 'PokemonEntity')
    for pokemon in Pokemon.objects.all():
        if not pokemon.title_ru:
            pokemon.title_ru = ''
        if not pokemon.title_en:
            pokemon.title_en = ''
        if not pokemon.title_jp:
            pokemon.title_jp = ''
        if not pokemon.description:
            pokemon.description = ''
    pokemon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20190724_1502'),
    ]

    operations = [
        migrations.RunPython(combine_pokemons),
    ]
